{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0767949f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "os.chdir('/Users/gabriele/PycharmProjects/RecSys')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "76e3ee33",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndentationError",
     "evalue": "unexpected indent (MultVAERecommender.py, line 9)",
     "output_type": "error",
     "traceback": [
      "Traceback \u001b[0;36m(most recent call last)\u001b[0m:\n",
      "  File \u001b[1;32m\"/Users/gabriele/opt/anaconda3/envs/jupyter/lib/python3.8/site-packages/IPython/core/interactiveshell.py\"\u001b[0m, line \u001b[1;32m3457\u001b[0m, in \u001b[1;35mrun_code\u001b[0m\n    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "\u001b[0;36m  File \u001b[0;32m\"/var/folders/6k/tknbbysd0fd7b8blw3n8zjjm0000gn/T/ipykernel_30965/156291111.py\"\u001b[0;36m, line \u001b[0;32m2\u001b[0;36m, in \u001b[0;35m<module>\u001b[0;36m\u001b[0m\n\u001b[0;31m    from src.Recommenders.Neural.MultVAERecommender import MultVAERecommender\u001b[0m\n",
      "\u001b[0;36m  File \u001b[0;32m\"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\"\u001b[0;36m, line \u001b[0;32m9\u001b[0m\n\u001b[0;31m    import tensorflow as tf\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mIndentationError\u001b[0m\u001b[0;31m:\u001b[0m unexpected indent\n"
     ]
    }
   ],
   "source": [
    "from src.HyperparameterTuning.SearchAbstractClass import SearchInputRecommenderArgs\n",
    "from src.Recommenders.Neural.MultVAERecommender import MultVAERecommender\n",
    "from Utils.utils import create_URM,create_ICM,combine_matrices\n",
    "from src.Evaluation.Evaluator import EvaluatorHoldout\n",
    "from src.Data_manager.split_functions.split_train_validation_random_holdout import split_train_in_two_percentage_global_sample\n",
    "from skopt.space import Real, Integer, Categorical\n",
    "import tensorflow as tf"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "2b9c9b88",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Warning: 13 (0.10 %) of 13650 users have no sampled items\n",
      "Warning: 25 (0.18 %) of 13650 users have no sampled items\n",
      "EvaluatorHoldout: Ignoring 13637 ( 0.1%) Users that have less than 1 test interactions\n",
      "EvaluatorHoldout: Ignoring 13625 ( 0.2%) Users that have less than 1 test interactions\n"
     ]
    }
   ],
   "source": [
    "URM = create_URM()\n",
    "ICM = create_ICM()\n",
    "\n",
    "\n",
    "URM_train_validation,URM_test = split_train_in_two_percentage_global_sample(URM,train_percentage=0.85)\n",
    "URM_train, URM_validation = split_train_in_two_percentage_global_sample(URM_train_validation,train_percentage=0.85)\n",
    "\n",
    "combined_matrices = combine_matrices(ICM=ICM, URM=URM_train)\n",
    "\n",
    "evaluator_test = EvaluatorHoldout(URM_test, cutoff_list=[10])\n",
    "evaluator_validation = EvaluatorHoldout(URM_validation, cutoff_list=[10])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "6e1746a5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n"
     ]
    },
    {
     "ename": "NameError",
     "evalue": "name 'tf' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/6k/tknbbysd0fd7b8blw3n8zjjm0000gn/T/ipykernel_30586/747059887.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mrecommender\u001b[0m\u001b[0;34m=\u001b[0m \u001b[0mMultVAERecommender\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mURM_train\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mcombined_matrices\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mrecommender\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, epochs, learning_rate, batch_size, dropout, total_anneal_steps, anneal_cap, p_dims, l2_reg, temp_file_folder, **earlystopping_kwargs)\u001b[0m\n\u001b[1;32m    294\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mp_dims\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mappend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mn_items\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    295\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 296\u001b[0;31m         \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcompat\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mv1\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreset_default_graph\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    297\u001b[0m         \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcompat\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mv1\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdisable_eager_execution\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    298\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'tf' is not defined"
     ]
    }
   ],
   "source": [
    "recommender= MultVAERecommender(URM_train=combined_matrices)\n",
    "recommender.fit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "83f06864",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Iteration No: 1 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 37, 'learning_rate': 0.00042840677978066863, 'batch_size': 906, 'l2_reg': 0.007300511809274324}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 0 Exception. Config: {'epochs': 37, 'learning_rate': 0.00042840677978066863, 'batch_size': 906, 'l2_reg': 0.007300511809274324} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 1 ended. Evaluation done at random point.\n",
      "Time taken: 0.0904\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 2 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 52, 'learning_rate': 0.0008237765982381979, 'batch_size': 618, 'l2_reg': 0.0044015002878652065}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 1 Exception. Config: {'epochs': 52, 'learning_rate': 0.0008237765982381979, 'batch_size': 618, 'l2_reg': 0.0044015002878652065} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 2 ended. Evaluation done at random point.\n",
      "Time taken: 0.0602\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 3 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 61, 'learning_rate': 0.0006659430587678502, 'batch_size': 54, 'l2_reg': 0.006735828233544561}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 2 Exception. Config: {'epochs': 61, 'learning_rate': 0.0006659430587678502, 'batch_size': 54, 'l2_reg': 0.006735828233544561} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Iteration No: 3 ended. Evaluation done at random point.\n",
      "Time taken: 0.0603\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 4 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 15, 'learning_rate': 0.0004744298227493364, 'batch_size': 468, 'l2_reg': 0.007491106599693431}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 3 Exception. Config: {'epochs': 15, 'learning_rate': 0.0004744298227493364, 'batch_size': 468, 'l2_reg': 0.007491106599693431} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 4 ended. Evaluation done at random point.\n",
      "Time taken: 0.0644\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 5 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 65, 'learning_rate': 0.0006752318579136623, 'batch_size': 796, 'l2_reg': 0.0003954087338574374}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 4 Exception. Config: {'epochs': 65, 'learning_rate': 0.0006752318579136623, 'batch_size': 796, 'l2_reg': 0.0003954087338574374} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 5 ended. Evaluation done at random point.\n",
      "Time taken: 0.0647\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 6 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 79, 'learning_rate': 0.0009099126564277671, 'batch_size': 392, 'l2_reg': 0.0009179069943765662}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 5 Exception. Config: {'epochs': 79, 'learning_rate': 0.0009099126564277671, 'batch_size': 392, 'l2_reg': 0.0009179069943765662} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 6 ended. Evaluation done at random point.\n",
      "Time taken: 0.0596\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 7 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 25, 'learning_rate': 6.530629313109569e-05, 'batch_size': 788, 'l2_reg': 0.00665329281835686}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 6 Exception. Config: {'epochs': 25, 'learning_rate': 6.530629313109569e-05, 'batch_size': 788, 'l2_reg': 0.00665329281835686} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 7 ended. Evaluation done at random point.\n",
      "Time taken: 0.0612\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 8 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 85, 'learning_rate': 8.143178210314248e-05, 'batch_size': 564, 'l2_reg': 0.00936266982290739}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 7 Exception. Config: {'epochs': 85, 'learning_rate': 8.143178210314248e-05, 'batch_size': 564, 'l2_reg': 0.00936266982290739} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 8 ended. Evaluation done at random point.\n",
      "Time taken: 0.0603\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 9 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 11, 'learning_rate': 0.00039023137069378393, 'batch_size': 96, 'l2_reg': 0.00954968982615498}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 8 Exception. Config: {'epochs': 11, 'learning_rate': 0.00039023137069378393, 'batch_size': 96, 'l2_reg': 0.00954968982615498} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 9 ended. Evaluation done at random point.\n",
      "Time taken: 0.0620\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 10 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 44, 'learning_rate': 0.0008792627741213741, 'batch_size': 630, 'l2_reg': 0.005862933454365548}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 9 Exception. Config: {'epochs': 44, 'learning_rate': 0.0008792627741213741, 'batch_size': 630, 'l2_reg': 0.005862933454365548} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Iteration No: 10 ended. Evaluation done at random point.\n",
      "Time taken: 0.0603\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 11 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 31, 'learning_rate': 0.0006346439856628833, 'batch_size': 335, 'l2_reg': 0.0010358392546287835}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 10 Exception. Config: {'epochs': 31, 'learning_rate': 0.0006346439856628833, 'batch_size': 335, 'l2_reg': 0.0010358392546287835} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 11 ended. Evaluation done at random point.\n",
      "Time taken: 0.0613\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 12 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 36, 'learning_rate': 0.0005317165810924383, 'batch_size': 848, 'l2_reg': 0.001835348530707837}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 11 Exception. Config: {'epochs': 36, 'learning_rate': 0.0005317165810924383, 'batch_size': 848, 'l2_reg': 0.001835348530707837} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 12 ended. Evaluation done at random point.\n",
      "Time taken: 0.0608\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 13 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 72, 'learning_rate': 0.0009332307937354752, 'batch_size': 885, 'l2_reg': 0.006203263890449259}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 12 Exception. Config: {'epochs': 72, 'learning_rate': 0.0009332307937354752, 'batch_size': 885, 'l2_reg': 0.006203263890449259} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 13 ended. Evaluation done at random point.\n",
      "Time taken: 0.0624\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 14 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 91, 'learning_rate': 0.000590886051790144, 'batch_size': 931, 'l2_reg': 0.003384085243798274}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 13 Exception. Config: {'epochs': 91, 'learning_rate': 0.000590886051790144, 'batch_size': 931, 'l2_reg': 0.003384085243798274} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 14 ended. Evaluation done at random point.\n",
      "Time taken: 0.0614\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 15 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 61, 'learning_rate': 2.6339482838245636e-05, 'batch_size': 321, 'l2_reg': 0.0024511160192182855}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 14 Exception. Config: {'epochs': 61, 'learning_rate': 2.6339482838245636e-05, 'batch_size': 321, 'l2_reg': 0.0024511160192182855} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 15 ended. Evaluation done at random point.\n",
      "Time taken: 0.0607\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 16 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 47, 'learning_rate': 3.9900588058658085e-05, 'batch_size': 172, 'l2_reg': 0.0002777076762247363}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 15 Exception. Config: {'epochs': 47, 'learning_rate': 3.9900588058658085e-05, 'batch_size': 172, 'l2_reg': 0.0002777076762247363} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 16 ended. Evaluation done at random point.\n",
      "Time taken: 0.0612\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 17 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 59, 'learning_rate': 3.183400603606836e-05, 'batch_size': 560, 'l2_reg': 0.005388508758061348}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 16 Exception. Config: {'epochs': 59, 'learning_rate': 3.183400603606836e-05, 'batch_size': 560, 'l2_reg': 0.005388508758061348} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Iteration No: 17 ended. Evaluation done at random point.\n",
      "Time taken: 0.0648\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 18 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 36, 'learning_rate': 0.0003524794871888509, 'batch_size': 240, 'l2_reg': 0.009892134150146262}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 17 Exception. Config: {'epochs': 36, 'learning_rate': 0.0003524794871888509, 'batch_size': 240, 'l2_reg': 0.009892134150146262} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 18 ended. Evaluation done at random point.\n",
      "Time taken: 0.0637\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 19 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 84, 'learning_rate': 0.00029588616021661713, 'batch_size': 754, 'l2_reg': 0.005627229486073745}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 18 Exception. Config: {'epochs': 84, 'learning_rate': 0.00029588616021661713, 'batch_size': 754, 'l2_reg': 0.005627229486073745} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 19 ended. Evaluation done at random point.\n",
      "Time taken: 0.0601\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 20 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 11, 'learning_rate': 0.0009513201743206653, 'batch_size': 40, 'l2_reg': 0.008632291202982501}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 19 Exception. Config: {'epochs': 11, 'learning_rate': 0.0009513201743206653, 'batch_size': 40, 'l2_reg': 0.008632291202982501} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 20 ended. Evaluation done at random point.\n",
      "Time taken: 0.0608\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 21 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 81, 'learning_rate': 0.0002820407056108903, 'batch_size': 313, 'l2_reg': 0.005977723777753671}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 20 Exception. Config: {'epochs': 81, 'learning_rate': 0.0002820407056108903, 'batch_size': 313, 'l2_reg': 0.005977723777753671} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 21 ended. Evaluation done at random point.\n",
      "Time taken: 0.0666\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 22 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 11, 'learning_rate': 0.00028263509490890793, 'batch_size': 412, 'l2_reg': 0.0012857714754450102}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 21 Exception. Config: {'epochs': 11, 'learning_rate': 0.00028263509490890793, 'batch_size': 412, 'l2_reg': 0.0012857714754450102} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 22 ended. Evaluation done at random point.\n",
      "Time taken: 0.0643\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 23 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 71, 'learning_rate': 0.00039200713302118173, 'batch_size': 503, 'l2_reg': 0.005485122740768401}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 22 Exception. Config: {'epochs': 71, 'learning_rate': 0.00039200713302118173, 'batch_size': 503, 'l2_reg': 0.005485122740768401} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 23 ended. Evaluation done at random point.\n",
      "Time taken: 0.0632\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 24 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 70, 'learning_rate': 0.0009766270669814947, 'batch_size': 642, 'l2_reg': 0.004561918461443941}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 23 Exception. Config: {'epochs': 70, 'learning_rate': 0.0009766270669814947, 'batch_size': 642, 'l2_reg': 0.004561918461443941} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Iteration No: 24 ended. Evaluation done at random point.\n",
      "Time taken: 0.0668\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 25 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 98, 'learning_rate': 0.0008861013900631908, 'batch_size': 820, 'l2_reg': 0.004699325786498134}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 24 Exception. Config: {'epochs': 98, 'learning_rate': 0.0008861013900631908, 'batch_size': 820, 'l2_reg': 0.004699325786498134} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 25 ended. Evaluation done at random point.\n",
      "Time taken: 0.0630\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 26 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 56, 'learning_rate': 0.00015549114949871178, 'batch_size': 336, 'l2_reg': 0.007789577603447388}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 25 Exception. Config: {'epochs': 56, 'learning_rate': 0.00015549114949871178, 'batch_size': 336, 'l2_reg': 0.007789577603447388} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 26 ended. Evaluation done at random point.\n",
      "Time taken: 0.0606\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 27 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 27, 'learning_rate': 0.0002315515801166289, 'batch_size': 401, 'l2_reg': 0.004039064998556793}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 26 Exception. Config: {'epochs': 27, 'learning_rate': 0.0002315515801166289, 'batch_size': 401, 'l2_reg': 0.004039064998556793} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 27 ended. Evaluation done at random point.\n",
      "Time taken: 0.0602\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 28 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 42, 'learning_rate': 0.00023479904050589524, 'batch_size': 173, 'l2_reg': 0.0036288153135945753}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 27 Exception. Config: {'epochs': 42, 'learning_rate': 0.00023479904050589524, 'batch_size': 173, 'l2_reg': 0.0036288153135945753} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 28 ended. Evaluation done at random point.\n",
      "Time taken: 0.0635\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 29 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 64, 'learning_rate': 0.0009394762413747862, 'batch_size': 350, 'l2_reg': 0.006179501223216827}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 28 Exception. Config: {'epochs': 64, 'learning_rate': 0.0009394762413747862, 'batch_size': 350, 'l2_reg': 0.006179501223216827} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "Iteration No: 29 ended. Evaluation done at random point.\n",
      "Time taken: 0.0616\n",
      "Function value obtained: 65504.0000\n",
      "Current minimum: 65504.0000\n",
      "Iteration No: 30 started. Evaluating function at random point.\n",
      "SearchBayesianSkopt: Testing config: {'epochs': 79, 'learning_rate': 0.0003055098364136984, 'batch_size': 195, 'l2_reg': 0.003861243075336172}\n",
      "MultVAERecommender: Using default Temp folder './result_experiments/__Temp_MultVAERecommender_30586/'\n",
      "SearchBayesianSkopt: Config 29 Exception. Config: {'epochs': 79, 'learning_rate': 0.0003055098364136984, 'batch_size': 195, 'l2_reg': 0.003861243075336172} - Exception: Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "\n",
      "\n",
      "SearchBayesianSkopt: Search interrupted. No valid config was found during the initial random initialization\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 464, in _objective_function\n",
      "    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 332, in _evaluate_on_validation\n",
      "    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/HyperparameterTuning/SearchAbstractClass.py\", line 304, in _fit_model\n",
      "    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,\n",
      "  File \"/Users/gabriele/PycharmProjects/RecSys/src/Recommenders/Neural/MultVAERecommender.py\", line 296, in fit\n",
      "    tf.compat.v1.reset_default_graph()\n",
      "NameError: name 'tf' is not defined\n"
     ]
    }
   ],
   "source": [
    "from src.HyperparameterTuning.SearchBayesianSkopt import SearchBayesianSkopt\n",
    "\n",
    "hyperparameters_range_dictionary = {\n",
    "    \"epochs\":Integer(10,100),\n",
    "    \"learning_rate\":Real(0.00001,0.001),\n",
    "    \"batch_size\":Integer(32,1000),\n",
    "    \"l2_reg\":Real(0.0001,0.01)\n",
    "}\n",
    "earlystopping_keywargs = {\"validation_every_n\": 5,\n",
    "                          \"stop_on_validation\": True,\n",
    "                          \"evaluator_object\": evaluator_validation,\n",
    "                          \"lower_validations_allowed\": 4,\n",
    "                          \"validation_metric\": \"MAP\",\n",
    "                          }\n",
    "recommender_input_args = SearchInputRecommenderArgs(\n",
    "    CONSTRUCTOR_POSITIONAL_ARGS = [combined_matrices],\n",
    "    CONSTRUCTOR_KEYWORD_ARGS = {},\n",
    "    FIT_POSITIONAL_ARGS = [],\n",
    "    FIT_KEYWORD_ARGS = earlystopping_keywargs\n",
    ")\n",
    "recommender_input_args_last_test = SearchInputRecommenderArgs(\n",
    "    CONSTRUCTOR_POSITIONAL_ARGS = [URM_train_validation],\n",
    "    CONSTRUCTOR_KEYWORD_ARGS = {},\n",
    "    FIT_POSITIONAL_ARGS = [],\n",
    "    FIT_KEYWORD_ARGS = earlystopping_keywargs\n",
    ")\n",
    "\n",
    "tuning_class = SearchBayesianSkopt(recommender_class=MultVAERecommender,\n",
    "                                   evaluator_validation=evaluator_validation,\n",
    "                                   evaluator_test=evaluator_test)\n",
    "\n",
    "n_cases = 100\n",
    "n_random_starts = n_cases*0.3\n",
    "output_folder_path = \"logs/\"\n",
    "\n",
    "tuning_class.search(recommender_input_args=recommender_input_args,\n",
    "                    recommender_input_args_last_test=recommender_input_args_last_test,\n",
    "                    hyperparameter_search_space=hyperparameters_range_dictionary,\n",
    "                    metric_to_optimize=\"MAP\",\n",
    "                    cutoff_to_optimize= 10,\n",
    "                    n_cases= n_cases,\n",
    "                    n_random_starts=n_random_starts,\n",
    "                    output_folder_path=output_folder_path,\n",
    "                    output_file_name_root=MultVAERecommender.RECOMMENDER_NAME,\n",
    "                    save_model=\"best\"\n",
    "                    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "339c336c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
